name: "Nix and Home Manager install "

on:
  push:
    branches: [ "**" ]
# Remove for now due to being unable to reach curl script in MR
# Also in the MR the jobs are duplicated so it may be unnecessary
#  pull_request:
#    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-without-clone:
    runs-on: ubuntu-latest
    steps:
        - run: sudo apt install curl -y
              && sh <(curl -L https://nixos.org/nix/install) --daemon --yes
              && source /etc/profile
              && nix --extra-experimental-features 'nix-command flakes' run github:EvanMusic14/home-manager/${{ github.ref }}#homeConfigurations."$USER".activationPackage

  setup-with-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: ./bin/setup

  setup-with-curl:
    runs-on: ubuntu-latest
    steps:
      - run: bash <(curl -L https://raw.githubusercontent.com/EvanMusic14/home-manager/${{ github.ref }}/bin/curl-setup)

  test-command:
    runs-on: ubuntu-latest
    steps:
      - run: [[ -f /snap/bin/firefox ]] && echo "Warning: There are snap packages installed that may conflict with nix packages" && echo "Run: sudo snap remove --purge firefox"
