# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for * branches
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  config-without-clone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: |
      #     cd $HOME
      #     pwd
      #     ls -lah
      #     if [[ -f $HOME/.bashrc ]]; then mv $HOME/.bashrc $HOME/.bashrc.backup; fi
      #     if [[ -f $HOME/.profile ]]; then mv $HOME/.profile $HOME/.profile.backup; fi
      #     ls -lah
    
      # # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install curl -y
              && sh <(curl -L https://nixos.org/nix/install) --daemon --yes
              && source /etc/profile
              && if [[ -f $HOME/.bashrc ]]; then mv ~/.bashrc ~/.bashrc.backup; fi
              && if [[ -f $HOME/.profile ]]; then mv ~/.profile ~/.profile.backup; fi
              && if [[ -f $HOME/.bash_profile ]]; then mv ~/.bash_profile ~/.bash_profile.backup; fi
              && nix --extra-experimental-features 'nix-command flakes' run github:EvanMusic14/home-manager/main#homeConfigurations."runner".activationPackage
              && source $HOME/.bashrc

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     sudo apt install curl -y
      #     sh <(curl -L https://nixos.org/nix/install) --daemon --yes
      #     source /etc/profile
      #     if [[ -f $HOME/.bashrc ]]; then mv $HOME/.bashrc $HOME/.bashrc.backup; fi
      #     if [[ -f $HOME/.profile ]]; then mv $HOME/.profile $HOME/.profile.backup; fi
      #     nix --extra-experimental-features 'nix-command flakes' run github:EvanMusic14/home-manager/${{ github.ref }}#homeConfigurations."runner".activationPackage
      #     source $HOME/.bashrc
